fa-solid fa-house
fa-solid fa-table-columns
fa-solid fa-users
fa-solid fa-user
fa-solid fa-user-plus
fa-solid fa-right-from-bracket
fa-solid fa-right-to-bracket
fa-solid fa-gear
fa-solid fa-envelope
fa-solid fa-plus
fa-solid fa-xmark
fa-solid fa-check
fa-solid fa-pen
fa-solid fa-pen-to-square
fa-solid fa-trash
fa-solid fa-grip-vertical
fa-solid fa-ellipsis-vertical
fa-solid fa-window-minimize
fa-solid fa-circle-info
fa-solid fa-triangle-exclamation
fa-solid fa-magnifying-glass
fa-solid fa-eye
fa-solid fa-bars
fa-solid fa-sun
fa-regular fa-sun
fa-solid fa-square
fa-regular fa-square
fa-regular fa-square-minus
fa-regular fa-square-plus
fa-solid fa-moon
fa-solid fa-chevron-down
fa-solid fa-chevron-up
fa-solid fa-chevron-right
fa-solid fa-arrow-right
fa-solid fa-tag
fa-solid fa-tags
fa-solid fa-list-check
fa-solid fa-comment
fa-solid fa-comments
fa-solid fa-paperclip
fa-solid fa-file
fa-solid fa-file-circle-question
fa-solid fa-circle-question
fa-solid fa-circle-check
fa-solid fa-image
fa-solid fa-calendar
fa-solid fa-calendar-day
fa-solid fa-calendar-check
fa-solid fa-mountain-sun
fa-solid fa-floppy-disk
fa-solid fa-circle-xmark
fa-solid fa-plug
fa-solid fa-plug-circle-bolt
fa-solid fa-bell
fa-solid fa-user-check
fa-regular fa-clock
fa-regular fa-handshake
fa-regular fa-copy
fa-solid fa-trash-can
fa-solid fa-table-list
fa-solid fa-sort
fa-solid fa-sort-up
fa-solid fa-sort-down
fa-solid fa-filter
fa-solid fa-bookmark
fa-solid fa-crosshairs
fa-solid fa-star-of-life
fa-solid fa-image
fa-regular fa-object-group
fa-solid fa-marker
fa-solid fa-map-location-dot
fa-regular fa-folder-open
